### ISSUE TITLE
build & release fails on resolving 'versions.json'

### ISSUE THREAD

**Issue by pkarl** [evanderkoogh/otel-cf-workers#164]
https://github.com/evanderkoogh/otel-cf-workers/actions/runs/10773791169/job/29874355832

```
Error: [check:type-esm] src/sdk.ts(32,27): error TS2307: Cannot find module '../versions.json' or its corresponding type declarations.
```

Reason appears to be that `npm run build` occurs before `npm run release` in the github action, and if the versions file isn't written already, the build script fails.

```
    // from .github/workflows/release.yml
        run: 'pnpm install --frozen-lockfile --child-concurrency=10'
      - name: Check the build
        run: pnpm build
      - name: 'Check for Errors'
        run: 'pnpm check'
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
```
